name = "backend"
compatibility_date = "2024-07-21"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWE1OGRlMGYtNmY4MC00MDFiLWI5OWYtNDhhZGY2MDhjNzVjIiwidGVuYW50X2lkIjoiYTVmODJiMTA5NmM0OGI5N2I2Y2M2ZDUzOWVhOTJhZGUxNDAyNWI1NjNlODNmMzFjNTI2YzBhNTFhNmY3ZjVlNyIsImludGVybmFsX3NlY3JldCI6IjhjZDdlYmE2LWYyODMtNDQzMC05NjMyLTYyYTc4YjE3YWFlYiJ9.T7MGGtu52W1NOKkKL3YcNYZztbe6Dqej8Yg-JZ18wAk"
JWT_SECRET="blogingwebsite"